test_anagram (__main__.TestExercice) ... FAIL
test_doubles (__main__.TestExercice) ... ok
test_frequence (__main__.TestExercice) ... ok
test_grades (__main__.TestExercice) ... FAIL
test_order (__main__.TestExercice) ... ok

======================================================================
FAIL: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_anagram
    'Erreur dans la vérification de l\'anagramme'
AssertionError: Lists differ: [False, False] != [True, False]

First differing element 0:
False
True

- [False, False]
+ [True, False] : Erreur dans la vérification de l'anagramme

======================================================================
FAIL: test_grades (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 68, in test_grades
    'Erreur dans les notes'
AssertionError: 'Sam' is not an instance of <class 'dict'> : First argument is not a dictionary

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
